var FindProxyForURL = function(init, profiles) {
    return function(url, host) {
        "use strict";
        var result = init, scheme = url.substr(0, url.indexOf(":"));
        do {
            result = profiles[result];
            if (typeof result === "function") result = result(url, host, scheme);
        } while (typeof result !== "string" || result.charCodeAt(0) === 43);
        return result;
    };
}("+auto switch", {
    "+auto switch": function(url, host, scheme) {
        "use strict";
        if (/(?:^|\.)localhost$/.test(host)) return "DIRECT";
        if (/(?:^|\.)google\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)pgyer\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)zicp\.fun$/.test(host)) return "+clash";
        if (/(?:^|\.)notion\.site$/.test(host)) return "DIRECT";
        if (/(?:^|\.)netmi\.com\.cn$/.test(host)) return "DIRECT";
        if (/(?:^|\.)alibaba-inc\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)dg-work\.cn$/.test(host)) return "+clash";
        if (/(?:^|\.)cli\.im$/.test(host)) return "DIRECT";
        if (/(?:^|\.)douyu\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)enncy\.cn$/.test(host)) return "DIRECT";
        if (/(?:^|\.)chaoxing\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)agemys\.vip$/.test(host)) return "+clash";
        if (/(?:^|\.)bimiacg\.net$/.test(host)) return "+clash";
        if (/(?:^|\.)gorui\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)vvbin\.cn$/.test(host)) return "+clash";
        if (/(?:^|\.)vini123\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)n10\.app$/.test(host)) return "+clash";
        if (/(?:^|\.)ngrok-free\.app$/.test(host)) return "+clash";
        if (/^192\.168\.50\.179$/.test(host)) return "DIRECT";
        if (/(?:^|\.)gstatic\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)viewspread\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)avatars\.githubusercontent\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)githubassets\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)github\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)bilibili\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)meiruanwang\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)topcpu\.net$/.test(host)) return "DIRECT";
        if (/(?:^|\.)disqus\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)globalsun\.io$/.test(host)) return "DIRECT";
        if (/(?:^|\.)b-cdn\.net$/.test(host)) return "DIRECT";
        if (/(?:^|\.)technical\.city$/.test(host)) return "DIRECT";
        if (/^192\.168\.50\.33$/.test(host)) return "DIRECT";
        if (/(?:^|\.)h5zhifu\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)algolia\.net$/.test(host)) return "DIRECT";
        if (/(?:^|\.)algolianet\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)bspapp\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)toutiaoimg\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)aiqingyu1314\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)aqdstatic\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)yhdm\.so$/.test(host)) return "DIRECT";
        if (/(?:^|\.)iqiyipic\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)alicdn\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)sinaimg\.cn$/.test(host)) return "DIRECT";
        if (/(?:^|\.)jd\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)51\.la$/.test(host)) return "DIRECT";
        if (/(?:^|\.)bcebos\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)doubanio\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)myqcloud\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)bdstatic\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)pstatp\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)csdnimg\.cn$/.test(host)) return "DIRECT";
        if (/(?:^|\.)csdn\.net$/.test(host)) return "DIRECT";
        if (/(?:^|\.)camo\.githubusercontent\.com$/.test(host)) return "+v2ray";
        if (/(?:^|\.)juejin\.cn$/.test(host)) return "DIRECT";
        if (/(?:^|\.)uviewui\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)dcloud\.net\.cn$/.test(host)) return "DIRECT";
        if (/(?:^|\.)dcloud\.io$/.test(host)) return "DIRECT";
        if (/(?:^|\.)aliyun\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)hangzhou2022\.cn$/.test(host)) return "+clash";
        if (/(?:^|\.)yuque\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)apache\.org$/.test(host)) return "DIRECT";
        if (/(?:^|\.)openai\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)sstz\.info$/.test(host)) return "+clash";
        if (/(?:^|\.)yinghuacd\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)jianshu\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)zdwp\.net$/.test(host)) return "DIRECT";
        if (/^172\.17\.0\.3$/.test(host)) return "DIRECT";
        if (/(?:^|\.)qq\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)doubleclick\.net$/.test(host)) return "DIRECT";
        if (/(?:^|\.)google\.com\.hk$/.test(host)) return "+clash";
        if (/(?:^|\.)leetcode\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)yhpdm\.net$/.test(host)) return "DIRECT";
        if (/(?:^|\.)netflix\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)netfly\.tv$/.test(host)) return "+clash";
        if (/(?:^|\.)zjdyit\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)freegpt\.one$/.test(host)) return "+clash";
        if (/(?:^|\.)zhihu\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)mypikpak\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)faceplusplus\.com\.cn$/.test(host)) return "DIRECT";
        if (/(?:^|\.)q1travel\.cloud$/.test(host)) return "DIRECT";
        if (/(?:^|\.)sciencenet\.cn$/.test(host)) return "+clash";
        if (/(?:^|\.)megvii\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)baidu\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)163\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)faceplusplus\.com$/.test(host)) return "+clash";
        if (/^192\.168\.50\.80$/.test(host)) return "+clash";
        if (/^192\.168\.176\.1$/.test(host)) return "+clash";
        if (/(?:^|\.)miui\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)chatapi\.art$/.test(host)) return "+clash";
        if (/(?:^|\.)yanhuangxueyuan\.com$/.test(host)) return "+clash";
        if (/^192\.168\.50\.90$/.test(host)) return "DIRECT";
        if (/(?:^|\.)$/.test(host)) return "+clash";
        if (/(?:^|\.)unrealengine\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)todesk\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)windows\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)singularityhub\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)openstreetmap\.org$/.test(host)) return "+clash";
        if (/(?:^|\.)infoq\.cn$/.test(host)) return "DIRECT";
        if (/(?:^|\.)gjtool\.cn$/.test(host)) return "+clash";
        if (/(?:^|\.)icons8\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)ntyou\.cc$/.test(host)) return "+clash";
        if (/(?:^|\.)bimiacg4\.net$/.test(host)) return "+clash";
        if (/^192\.168\.50\.74$/.test(host)) return "DIRECT";
        if (/(?:^|\.)alipay\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)mapbox\.cn$/.test(host)) return "+clash";
        if (/(?:^|\.)amap\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)gitee\.io$/.test(host)) return "DIRECT";
        if (/^122\.224\.94\.109$/.test(host)) return "DIRECT";
        if (/(?:^|\.)iconfont\.cn$/.test(host)) return "DIRECT";
        if (/(?:^|\.)huya\.com$/.test(host)) return "DIRECT";
        if (/^122\.224\.94\.108$/.test(host)) return "DIRECT";
        if (/(?:^|\.)zj\.gov\.cn$/.test(host)) return "+clash";
        if (/(?:^|\.)modao\.cc$/.test(host)) return "DIRECT";
        if (/(?:^|\.)vipstone\.github\.io$/.test(host)) return "+clash";
        if (/(?:^|\.)youtube\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)lanhuapp\.com$/.test(host)) return "DIRECT";
        if (/^1\.0\.243\.10$/.test(host)) return "DIRECT";
        if (/(?:^|\.)ktm\.sh$/.test(host)) return "+clash";
        if (/(?:^|\.)stackoverflow\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)http:\/\/googleapis\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)antv\.vision$/.test(host)) return "+clash";
        if (/(?:^|\.)codepen\.io$/.test(host)) return "+clash";
        if (/(?:^|\.)xn--centospinggithub-vq9yxb669luirto6f5z0j\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)twitter\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)vitejs\.dev$/.test(host)) return "+clash";
        if (/(?:^|\.)flyfishclub\.com$/.test(host)) return "DIRECT";
        if (/^192\.168\.50\.52$/.test(host)) return "DIRECT";
        if (/(?:^|\.)reddit\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)hackmd\.io$/.test(host)) return "+clash";
        if (/(?:^|\.)donfalcon\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)vueuse\.org$/.test(host)) return "+clash";
        if (/(?:^|\.)chessengines\.org$/.test(host)) return "+clash";
        if (/(?:^|\.)android\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)app\.netlify\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)netlify\.app$/.test(host)) return "+clash";
        if (/(?:^|\.)sli\.dev$/.test(host)) return "+clash";
        if (/(?:^|\.)discord\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)harvard\.edu$/.test(host)) return "+clash";
        if (/(?:^|\.)medium\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)wikiwand\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)webtorrent\.io$/.test(host)) return "+clash";
        if (/(?:^|\.)stackexchange\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)sk89q\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)littleskin\.cn$/.test(host)) return "+clash";
        if (/^20\.205\.243\.166$/.test(host)) return "+clash";
        if (/(?:^|\.)ngrok\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)t\.me$/.test(host)) return "+clash";
        if (/(?:^|\.)googleusercontent\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)steamcommunity\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)vuejs\.org$/.test(host)) return "+clash";
        if (/(?:^|\.)flexclip\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)makeapie\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)eleme\.io$/.test(host)) return "+clash";
        if (/(?:^|\.)githubd\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)emacs-china\.org$/.test(host)) return "+clash";
        if (/(?:^|\.)microsoft\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)raw\.githubusercontent\.com$/.test(host)) return "+clash";
        if (/^121\.4\.141\.47$/.test(host)) return "DIRECT";
        if (/(?:^|\.)mapbox\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)typora\.io$/.test(host)) return "+clash";
        if (/(?:^|\.)youzan\.github\.io$/.test(host)) return "+clash";
        if (/(?:^|\.)element-plus\.org$/.test(host)) return "+clash";
        if (/(?:^|\.)mctalks\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)wikipedia\.org$/.test(host)) return "+clash";
        if (/(?:^|\.)factpedia\.org$/.test(host)) return "+clash";
        if (/(?:^|\.)antfu\.me$/.test(host)) return "+clash";
        if (/(?:^|\.)rawgit\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)codingwithsara\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)imjad\.cn$/.test(host)) return "+clash";
        if (/(?:^|\.)2heng\.xin$/.test(host)) return "+clash";
        if (/(?:^|\.)joinmastodon\.org$/.test(host)) return "+clash";
        if (/(?:^|\.)littlefo\.rest$/.test(host)) return "+clash";
        if (/(?:^|\.)jsfiddle\.net$/.test(host)) return "+clash";
        if (/(?:^|\.)qiman56\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)codeantenna\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)igoutu\.cn$/.test(host)) return "+clash";
        if (/(?:^|\.)live\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)videojs\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)gitlab\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)wakatime\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)jenkins\.io$/.test(host)) return "+clash";
        if (/(?:^|\.)microsoftonline\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)jb\.gg$/.test(host)) return "+clash";
        if (/(?:^|\.)keil\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)gitbooks\.io$/.test(host)) return "+clash";
        if (/(?:^|\.)netsarang\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)steampowered\.com$/.test(host)) return "+clash";
        if (/^internal\.example\.com$/.test(host)) return "DIRECT";
        if (/(?:^|\.)example\.com$/.test(host)) return "+clash";
        if (/(?:^|\.)githubusercontent\.com$/.test(host)) return "+clash";
        return "+__ruleListOf_auto switch";
    },
    "+__ruleListOf_auto switch": function(url, host, scheme) {
        "use strict";
        if (/^\{"payload":\{"allShortcutsEnabled":true,"fileTree":\{"":\{"items":\[\{"name":"OmegaRules_auto_switch\.sorl","path":"OmegaRules_auto_switch\.sorl","contentType":"file"\}],"totalCount":1\}\},"fileTreeProcessingTime":1\.768215,"foldersToFetch":\[],"reducedMotionEnabled":"system","repo":\{"id":685858362,"defaultBranch":"main","name":"switchyOmegaPac","ownerLogin":"yinwusaya","currentUserCanPush":true,"isFork":false,"isEmpty":false,"createdAt":"2023-09-01T15:07:10\.000\+08:00","ownerAvatar":"https:\/\/avatars\.githubusercontent\.com\/u\/44662769.v=4","public":false,"private":true,"isOrgOwned":false\},"symbolsExpanded":true,"treeExpanded":true,"refInfo":\{"name":"main","listCacheKey":"v0:1693552101\.0","canEdit":true,"refType":"branch","currentOid":"bbfbf7d2f72f120b89dc7b7877fc0da5af39536b"\},"path":"OmegaRules_auto_switch\.sorl","currentUser":\{"id":44662769,"login":"yinwusaya","userEmail":"chenliangliang1468871115@gmail\.com"\},"blob":\{"rawLines":\["\[SwitchyOmega Conditions]","; Require: SwitchyOmega >= 2\.3\.2","; Date: 2023\/9\/1","; Usage: https:\/\/github\.com\/FelisCatus\/SwitchyOmega\/wiki\/RuleListUsage","",".*\.localhost","!.*\.google\.com",".*\.pgyer\.com","!.*\.zicp\.fun",".*\.notion\.site",".*\.netmi\.com\.cn",".*\.alibaba-inc\.com","!.*\.dg-work\.cn",".*\.cli\.im",".*\.douyu\.com",".*\.enncy\.cn",".*\.chaoxing\.com","!.*\.agemys\.vip","!.*\.bimiacg\.net",".*\.gorui\.com","!.*\.vvbin\.cn","!.*\.vini123\.com","!.*\.n10\.app","!.*\.ngrok-free\.app","192\.168\.50\.179","!.*\.gstatic\.com","!.*\.viewspread\.com","!.*\.avatars\.githubusercontent\.com","!.*\.githubassets\.com","!.*\.github\.com",".*\.bilibili\.com",".*\.meiruanwang\.com",".*\.topcpu\.net",".*\.disqus\.com",".*\.globalsun\.io",".*\.b-cdn\.net",".*\.technical\.city","192\.168\.50\.33",".*\.h5zhifu\.com",".*\.algolia\.net",".*\.algolianet\.com",".*\.bspapp\.com",".*\.toutiaoimg\.com",".*\.aiqingyu1314\.com",".*\.aqdstatic\.com",".*\.yhdm\.so",".*\.iqiyipic\.com",".*\.alicdn\.com",".*\.sinaimg\.cn",".*\.jd\.com",".*\.51\.la",".*\.bcebos\.com",".*\.doubanio\.com",".*\.myqcloud\.com",".*\.bdstatic\.com",".*\.pstatp\.com",".*\.csdnimg\.cn",".*\.csdn\.net",".*\.camo\.githubusercontent\.com",".*\.juejin\.cn",".*\.uviewui\.com",".*\.dcloud\.net\.cn",".*\.dcloud\.io",".*\.aliyun\.com","!.*\.hangzhou2022\.cn",".*\.yuque\.com",".*\.apache\.org","!.*\.openai\.com","!.*\.sstz\.info","!.*\.yinghuacd\.com",".*\.jianshu\.com",".*\.zdwp\.net","172\.17\.0\.3",".*\.qq\.com",".*\.doubleclick\.net","!.*\.google\.com\.hk",".*\.leetcode\.com",".*\.yhpdm\.net","!.*\.netflix\.com","!.*\.netfly\.tv",".*\.zjdyit\.com","!.*\.freegpt\.one",".*\.zhihu\.com","!.*\.mypikpak\.com",".*\.faceplusplus\.com\.cn",".*\.q1travel\.cloud","!.*\.sciencenet\.cn",".*\.megvii\.com",".*\.baidu\.com",".*\.163\.com","!.*\.faceplusplus\.com","!192\.168\.50\.80","!192\.168\.176\.1",".*\.miui\.com","!.*\.chatapi\.art","!.*\.yanhuangxueyuan\.com","192\.168\.50\.90","!.*\.","!.*\.unrealengine\.com",".*\.todesk\.com","!.*\.windows\.com","!.*\.singularityhub\.com","!.*\.openstreetmap\.org",".*\.infoq\.cn","!.*\.gjtool\.cn","!.*\.icons8\.com","!.*\.ntyou\.cc","!.*\.bimiacg4\.net","192\.168\.50\.74",".*\.alipay\.com","!.*\.mapbox\.cn",".*\.amap\.com",".*\.gitee\.io","122\.224\.94\.109",".*\.iconfont\.cn",".*\.huya\.com","122\.224\.94\.108","!.*\.zj\.gov\.cn",".*\.modao\.cc","!.*\.vipstone\.github\.io","!.*\.youtube\.com",".*\.lanhuapp\.com","1\.0\.243\.10","!.*\.ktm\.sh","!.*\.stackoverflow\.com","!.*\.http:\/\/googleapis\.com","!.*\.antv\.vision","!.*\.codepen\.io","!.*\.xn--centospinggithub-vq9yxb669luirto6f5z0j\.com","!.*\.twitter\.com","!.*\.vitejs\.dev",".*\.flyfishclub\.com","192\.168\.50\.52","!.*\.reddit\.com","!.*\.hackmd\.io","!.*\.donfalcon\.com","!.*\.vueuse\.org","!.*\.chessengines\.org","!.*\.android\.com","!.*\.app\.netlify\.com","!.*\.netlify\.app","!.*\.sli\.dev","!.*\.discord\.com","!.*\.harvard\.edu","!.*\.medium\.com","!.*\.wikiwand\.com","!.*\.webtorrent\.io","!.*\.stackexchange\.com","!.*\.sk89q\.com","!.*\.littleskin\.cn","!20\.205\.243\.166","!.*\.ngrok\.com","!.*\.t\.me","!.*\.googleusercontent\.com","!.*\.steamcommunity\.com","!.*\.vuejs\.org","!.*\.flexclip\.com","!.*\.makeapie\.com","!.*\.eleme\.io","!.*\.githubd\.com","!.*\.emacs-china\.org","!.*\.microsoft\.com","!.*\.raw\.githubusercontent\.com","121\.4\.141\.47","!.*\.mapbox\.com","!.*\.typora\.io","!.*\.youzan\.github\.io","!.*\.element-plus\.org","!.*\.mctalks\.com","!.*\.wikipedia\.org","!.*\.factpedia\.org","!.*\.antfu\.me","!.*\.rawgit\.com","!.*\.codingwithsara\.com","!.*\.imjad\.cn","!.*\.2heng\.xin","!.*\.joinmastodon\.org","!.*\.littlefo\.rest","!.*\.jsfiddle\.net","!.*\.qiman56\.com","!.*\.codeantenna\.com","!.*\.igoutu\.cn","!.*\.live\.com","!.*\.videojs\.com","!.*\.gitlab\.com","!.*\.wakatime\.com","!.*\.jenkins\.io","!.*\.microsoftonline\.com","!.*\.jb\.gg","!.*\.keil\.com","!.*\.gitbooks\.io","!.*\.netsarang\.com","!.*\.steampowered\.com","internal\.example\.com","!.*\.example\.com","!.*\.githubusercontent\.com"],"stylingDirectives":\[\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[],\[]],"csv":null,"csvError":null,"dependabotInfo":\{"showConfigurationBanner":null,"configFilePath":null,"networkDependabotPath":"\/yinwusaya\/switchyOmegaPac\/network\/updates","dismissConfigurationNoticePath":"\/settings\/dismiss-notice\/dependabot_configuration_notice","configurationNoticeDismissed":false,"repoAlertsPath":"\/yinwusaya\/switchyOmegaPac\/security\/dependabot","repoSecurityAndAnalysisPath":"\/yinwusaya\/switchyOmegaPac\/settings\/security_analysis","repoOwnerIsOrg":false,"currentUserCanAdminRepo":true\},"displayName":"OmegaRules_auto_switch\.sorl","displayUrl":"https:\/\/github\.com\/yinwusaya\/switchyOmegaPac\/blob\/main\/OmegaRules_auto_switch\.sorl.raw=true","headerInfo":\{"blobSize":"2\.99 KB","deleteInfo":\{"deleteTooltip":"Delete this file"\},"editInfo":\{"editTooltip":"Edit this file"\},"ghDesktopPath":"https:\/\/desktop\.github\.com","gitLfsPath":null,"onBranch":true,"shortPath":"6aab140","siteNavLoginPath":"\/login.return_to=https%3A%2F%2Fgithub\.com%2Fyinwusaya%2FswitchyOmegaPac%2Fblob%2Fmain%2FOmegaRules_auto_switch\.sorl%3F_%3D1693552119442","isCSV":false,"isRichtext":false,"toc":null,"lineInfo":\{"truncatedLoc":"196","truncatedSloc":"195"\},"mode":"file"\},"image":false,"isCodeownersFile":null,"isPlain":false,"isValidLegacyIssueTemplate":false,"issueTemplateHelpUrl":"https:\/\/docs\.github\.com\/articles\/about-issue-and-pull-request-templates","issueTemplate":null,"discussionTemplate":null,"language":null,"languageID":null,"large":false,"loggedIn":true,"newDiscussionPath":"\/yinwusaya\/switchyOmegaPac\/discussions\/new","newIssuePath":"\/yinwusaya\/switchyOmegaPac\/issues\/new","planSupportInfo":\{"repoIsFork":null,"repoOwnedByCurrentUser":null,"requestFullPath":"\/yinwusaya\/switchyOmegaPac\/blob\/main\/OmegaRules_auto_switch\.sorl._=1693552119442","showFreeOrgGatedFeatureMessage":null,"showPlanSupportBanner":null,"upgradeDataAttributes":null,"upgradePath":null\},"publishBannersInfo":\{"dismissActionNoticePath":"\/settings\/dismiss-notice\/publish_action_from_dockerfile","dismissStackNoticePath":"\/settings\/dismiss-notice\/publish_stack_from_file","releasePath":"\/yinwusaya\/switchyOmegaPac\/releases\/new.marketplace=true","showPublishActionBanner":false,"showPublishStackBanner":false\},"renderImageOrRaw":false,"richText":null,"renderedFileInfo":null,"shortPath":null,"tabSize":8,"topBannersInfo":\{"overridingGlobalFundingFile":false,"globalPreferredFundingPath":null,"repoOwner":"yinwusaya","repoName":"switchyOmegaPac","showInvalidCitationWarning":false,"citationHelpUrl":"https:\/\/docs\.github\.com\/en\/github\/creating-cloning-and-archiving-repositories\/creating-a-repository-on-github\/about-citation-files","showDependabotConfigurationBanner":null,"actionsOnboardingTip":null\},"truncated":false,"viewable":true,"workflowRedirectUrl":null,"symbols":\{"timedOut":false,"notAnalyzed":true,"symbols":\[]\}\},"copilotInfo":\{"documentationUrl":"https:\/\/docs\.github\.com\/copilot\/overview-of-github-copilot\/about-github-copilot-for-individuals","notices":\{"codeViewPopover":\{"dismissed":false,"dismissPath":"\/settings\/dismiss-notice\/code_view_copilot_popover"\}\},"userAccess":\{"accessAllowed":false,"hasSubscriptionEnded":false,"orgHasCFBAccess":false,"userHasCFIAccess":false,"userHasOrgs":false,"userIsOrgAdmin":false,"userIsOrgMember":false,"business":null,"featureRequestInfo":null\}\},"csrf_tokens":\{"\/yinwusaya\/switchyOmegaPac\/branches":\{"post":"zpRD-H3sqBVZO5TksCXuSbZwJr-3vQewuSthxbBd1ovPXcw0k7mhnPTSTTQrAkLnb6uKHaKDaGuTZ5Ik2_Oy0Q"\},"\/repos\/preferences":\{"post":"QVa9tV0y7e_a8Rhn9E0mpHGEpMjtWzoHRbD7SufX-kdJugj0iZlkksuXhHGP4q1KvgKdWjy3OrbawINHK1241g"\}\}\},"title":"switchyOmegaPac\/OmegaRules_auto_switch\.sorl at main \u00b7 yinwusaya\/switchyOmegaPac"\}$/.test(host)) return "DIRECT";
        return "+clash";
    },
    "+clash": function(url, host, scheme) {
        "use strict";
        if (/^127\.0\.0\.1$/.test(host) || /^::1$/.test(host) || /^localhost$/.test(host)) return "DIRECT";
        return "PROXY 127.0.0.1:7890";
    },
    "+v2ray": function(url, host, scheme) {
        "use strict";
        if (/^127\.0\.0\.1$/.test(host) || /^::1$/.test(host) || /^localhost$/.test(host)) return "DIRECT";
        return "PROXY 127.0.0.1:17890";
    }
});